import { LoginScreen } from "./screens/loginScreen.slint";
import { Dashboard } from "./screens/dashboard.slint"; // Import new dashboard
import { AuthStore, AppState } from "./store.slint";

export { AuthStore, AppState }

export component MainController inherits Window {
    title: "Aura POS System";
    width: 1200px;
    height: 800px;

    if (AppState.active_screen == "login") : LoginScreen {}

    // Use the new component here
    if (AppState.active_screen == "dashboard") : Dashboard {}
}
